name: Run WRF Downloader

on:
  schedule:
    - cron: "0 10 * * *"  # Menjalankan setiap hari pada pukul 10:00 UTC
  workflow_dispatch:  # Memungkinkan menjalankan secara manual

permissions:
  contents: write  # Memberikan izin untuk push ke repository

jobs:
  download_and_process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Hindari konflik dengan GITHUB_TOKEN
          fetch-depth: 0  # Pastikan semua history Git tersedia

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python opencv-python-headless numpy requests

      - name: Run WRF downloader script
        run: python wrf_downloader.py

      - name: Upload Forecast Maps
        uses: actions/upload-artifact@v4
        with:
          name: forecast-maps
          path: wrf_wcpl/**/*.png
          compression-level: 0
            
      - name: Debug files
        run: ls -R wrf_wcpl/

      - name: Commit and Push Forecast Maps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ajuneuh/andat_pracu_2025.git
          git add wrf_wcpl/
          git commit -m "Update forecast maps for $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push origin main
