name: Run WRF Downloader

on:
  schedule:
    - cron: "0 10 * * *"  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Memungkinkan menjalankan secara manual

jobs:
  download_and_process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python opencv-python-headless numpy requests

      - name: Run WRF downloader script
        run: python wrf_downloader.py

      - name: Upload generated images
        uses: actions/upload-artifact@v4
        with:
          name: wrf-images
          path: |
            wrf_wcpl/${{ steps.date.outputs.date }}/*.png
            
      - name: Debug files
        run: ls -R wrf_wcpl/

